### ISSUE TITLE
2 erreurs

### ISSUE THREAD

**Issue by mimo38** [jperon/sevin#1]
- [x] Notre-Dame des bois ]https://github.com/jperon/sevin/blob/ddd66a5cec0eca4934b7c74317cd90927d425e11/Partitions/NotreDameDesBois/NotreDameDesBois.ly#L48 : "Sous les grand**s**" ligne 48

- [x] Notre-Dame Angevine https://github.com/jperon/sevin/blob/ddd66a5cec0eca4934b7c74317cd90927d425e11/Partitions/NotreDameAngevine/NotreDameAngevine.ly#L82

**Comment by jperon** [comment]
Merci beaucoup ! Si vous voyez d'autres fautes, n'hésitez pas à utiliser l'interface de github pour modifier vous-même les fichiers : cela créera automatiquement une *pull request*, qu'il n'y aura plus qu'à fusionner pour intégrer les corrections.

**Comment by mimo38** [comment]
Je ne savais pas que c'était possible, je découvre les arcanes de github ! Trop puissant pour moi. Je n'arrive pas à faire agir le .gitignore… entre autres.
